services:
  db:
    image: mariadb:latest
    restart: always
    # Important en test local mais pas en prod
    environment:
      MYSQL_ROOT_PASSWORD: roottest
      MYSQL_USER: test
      MYSQL_PASSWORD: testpass
      MYSQL_DATABASE: wordpress
    ports:
        - '3306:3306'
    volumes:
        - ${PWD}/mariadb/:/var/lib/mysql/
  wp:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=test
      - WORDPRESS_DB_PASSWORD=testpass
      - WORDPRESS_DB_NAME=wordpress
    # Important : db = nom du service de BDD inscris plus haut 
    # Les id WORDPRESS_ doivent être les même que les id MYSQL_
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
      - wp
    ports:
      - 81:80
    environment:
      PMA_HOST: db

volumes:
  wp_data:

      