FROM php:8.2-fpm-alpine

# Installation des extensions PHP requises et de WP-CLI
RUN apk add --no-cache curl mariadb-client \
    && docker-php-ext-install mysqli \
    && curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

# Répertoire de travail
WORKDIR /var/www/html

# Ajout du script de configuration et du template wordpress au conteneur
COPY setup.sh /usr/local/bin/
COPY wp-config-template.php /tmp/

# Rendre le script exécutable
RUN chmod +x /usr/local/bin/setup.sh

# Ecouter sur le port 9000
EXPOSE 9000

# Point de lancement du conteneur sur script
ENTRYPOINT ["/usr/local/bin/setup.sh"]
